### ISSUE TITLE
[Bug]: Puppetserver command not getting correct ca_server and ca_port

### ISSUE THREAD

**Issue by dotconfig404** [OpenVoxProject/container-openvoxserver#52]
### Is this a critical security issue?

- [x] This is not a security issue.

### Describe the Bug

Hi, 

when not setting the `ca_server` and `ca_port` explicitly they are not written to the puppet.conf. This causes issues when trying to use `puppetserver ca` commands from within the container. 

### Expected Behavior

When running `puppetserver ca` commands from within the container the correct hostname and port should be used.  

### Steps to Reproduce

`docker compose up` using this `docker-compose.yml`
```yaml
services:
  openvox:
    image: ghcr.io/openvoxproject/openvoxserver:8.8.0-latest
    container_name: 'openvox'
    hostname: 'example.com'
    environment:
      CA_HOSTNAME: 'example.com'
      CA_PORT: '8144'
```
Execute `docker exec -it openvox puppetserver ca list`:

```
Fatal error when running action 'list'
  Error: Failed connecting to https://puppet:8140/puppet-ca/v1/certificate_statuses/any_key?state=requested
  Root cause: Failed to open TCP connection to puppet:8140 (getaddrinfo: Name or service not known)
```

### Environment

Ubuntu 24.04
Version 8.8.0

### Additional Context

I believe this [issue](https://github.com/OpenVoxProject/container-openvoxserver/issues/24) is an example for why explicitly setting `ca_server` and `ca_port` might generally be a good idea to make the container more resilient. Although pehaps in the case of explictly changing the config the command line argument should perhaps be omitted anyways? 

 
I was not entirely sure of whether to put this as a bug, but ultimately I think it can be regarded as one, since managing a CA server can require manual intervention and the command needed for that does not work without doing some additional adjustments.

### Relevant log output

```shell

```
